version: '3.7'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to bootstrap postgres
      - ./sql/create_dbs.sql:/docker-entrypoint-initdb.d/create_dbs.sql
